version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: test_wp
       MYSQL_USER: test_wp
       MYSQL_PASSWORD: test_wp

   wordpress:
     image: bedrock-wp:latest
     depends_on:
       - db
